---
name: Track releases

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: Run release-please
    uses: bodgit/workflows/.github/workflows/release.yml@f2ad91a9e0ba58982cdc180b62f69555ddf17d06 # v1.0.0
